os: linux

dist: xenial

sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - '11'
  - 'lts/*'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        chrome: stable
        firefox: latest
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless
      script:
        - npm run travis
    - os: osx
      osx_image: xcode10.1
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis
    - os: osx
      osx_image: xcode9.2
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis

git:
  depth: 3

cache: npm

script:
  - npm run lint
  - npm run mocha
